Imports System
Imports NXOpen
Imports NXOpen.UF

Module FacePointSelection
Sub Main (ByVal args() As String)

    Dim theSession As Session = Session.GetSession()
    Dim theUfSession As UFSession = UFSession.GetUFSession()
    Dim theUI As UI = UI.GetUI()
    Dim theLW As ListingWindow = theSession.ListingWindow
    Dim pointTag As NXOpen.Tag
    Dim basePoint(2) As Double
    Dim response As Integer

    theUfSession.Ui.LockUgAccess(NXOpen.UF.UFConstants.UF_UI_FROM_CUSTOM)
    theUfSession.Ui.PointConstruct("Select Point on Face", UFUi.PointBaseMethod.PointOnSurfacePt, pointTag, basePoint, response)
    theUfSession.Ui.UnlockUgAccess(NXOpen.UF.UFConstants.UF_UI_FROM_CUSTOM)
    If response <> UFConstants.UF_UI_OK Then Return
    
    Dim pointObj As NXOpen.Point =  CType(Utilities.NXObjectManager.Get(pointTag), NXOpen.Point)

    Dim n_parents As Integer
    Dim parents() As Tag = Nothing
    Dim type, subtype As Integer

    theUFSession.So.AskParents(pointTag, UFConstants.UF_SO_ASK_ALL_PARENTS, n_parents, parents)
    theLW.Open()

    For ii As Integer = 0 To n_parents - 1
        theUFSession.Obj.AskTypeAndSubtype(parents(ii), type, subtype)
        Dim parentObj As TaggedObject = Utilities.NXObjectManager.Get(parents(ii))

        If TypeOf parentObj Is NXOpen.Face Then
            Dim dispObj As DisplayableObject = CType(parentObj, NXOpen.DisplayableObject)
            dispObj.Highlight()

            Dim viewTag As NXOpen.Tag = theSession.Parts.Work.Views.WorkView.Tag
            Dim myColor As UFObj.DispProps
            myColor.color = 186
            theUFSession.Disp.DisplayTemporaryPoint(viewTag, UFDisp.ViewType.UseCursor, _
                basePoint, myColor, UFDisp.PolyMarker.Asterisk)
                              
            Dim msg As String = String.Format("Coordinates: {0}{1}Parent: {2} Type: {3} Subtype: {4} Layer: {5}",
                pointObj.Coordinates.ToString, Environment.Newline, dispObj.ToString(), type, subtype, dispObj.Layer)
            theUI.NXMessageBox.Show("Parent", NXMessageBox.DialogType.Information, msg)

            dispObj.Unhighlight()
        End If
    Next
        
End Sub
End Module
